### PR TITLE
Add icon link and persistent volume for GoCD server

### PR DESCRIPTION
**Pull request by GaneshSPatil**

### CODE REVIEW

**Comment by GaneshSPatil** [comment]
Volume mounts for `/home/go` ?

**Comment by ketan** [comment]
> Volume mounts for /home/go ?

That may not be appropriate with shared caches. For e.g. `mvn install` on one agent will install to `/home/go/.m2` and all agents will see it.

**Comment by arvindsv** [comment]
Not sure why we would need volume mounts for agents, especially with elastic agents. If not for elastic agents, maybe it's appropriate.

**Comment by GaneshSPatil** [comment]
@arvindsv -- it's not for elastic agents, it's for normal multiple agent deployment.

**Comment by varshavaradarajan** [comment]
I think this is a opener for the discussion around whether the one helm chart should  be used for both server and agent. Its something that could be listed as a dependency in requirements.yaml should users choose to have a static agent on k8s

The advantage of having 2 helm charts is that the agent helm chart can then be used for elastic agents. 

Coming back to the point around volume mounts for agents. I think that considering that the helm chart will not just be used for our elastic agent plugin, but also as a stand alone thing, agent logs seem the only useful thing to store (I think). Although doing `kubectl logs` on a pod would get us the info,  volume mount on agent doesn't seem necessary.

But, why are we discussing this on a PR which adds support for persistent volume to the server? :)

**Pull request merged**
